[user]
name = "Mark Derricutt"
email = "mark.derricutt@smxemail.com"

[ui]
#diff-editor = "bcompare"
#diff-editor = "diffedit3"
#diff-editor = "ksdiff"
default-command = "ls"
editor = "hx"
#merge-editor = ["araxisgitmerge", "-wait", "-2", "$left", "$right", "$output"]
#merge-editor = ["bcompare", "-wait", "$left", "$right", "$base", "$output"]
merge-editor = ["ksdiff", "--merge", "--output", "$output", "--base", "$base", "$left", "$right"]
#merge-editor =  ["mergiraf", "merge", "$base", "$left", "$right", "-o", "$output", "--fast"]
log-word-wrap = true
log-synthetic-elided-nodes = true
#graph.style = "square"
#diff.tool = ["delta", "--dark", "--diff-stat-align-width=80"]
diff-formatter = "difft"
diff-args = ["--color=always", "$left", "$right"]

pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }

# Options: diff, snapshot, git
conflict-marker-style = "git"

[git]
push-bookmark-prefix = "feature/"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
write-change-id-header=true

[merge-tools.diffedit3]
# Replace `program` with the full path to the
# binary if it is not in your PATH.

#program = "diffedit3"
#edit-args = ["$left", "$right", "$output"]

[merge-tools.mergiraf]
program = "mergiraf"
merge-args = ["merge", "$base", "$left", "$right", "-o", "$output", "--fast"]
merge-conflict-exit-codes = [1]
conflict-marker-style = "git"

[template-aliases]
custom_log_summary = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(author.email(), author.email().local(), email_placeholder),
        format_timestamp(commit_timestamp(self)),
        bookmarks,
        tags,
        working_copies,
        if(git_head, label("git_head", "git_head()")),
        format_short_commit_id(commit_id),
        if(conflict, label("conflict", "conflict")),
        if(config("ui.show-cryptographic-signatures").as_boolean(),
          format_short_cryptographic_signature(signature)),
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(
            if(empty, "empty"),
            description_placeholder ++ "\n" ++ self.diff().summary()),
        ),
      ) ++ "\n",
    ),
  )
)
'''

[templates]
aliases.'format_timestamp(timestamp)' = 'timestamp.ago()'

#draft_commit_description = '''
#concat(
#  description,
#  if(
#    !description.contains("Change-Id: I"),
#    "\n\n" ++ "Change-Id: I6a6a636c" ++ change_id.normal_hex() ++ "\n",
#  ),
#  surround(
#    "\nJJ: This commit contains the following changes:\n", "",
#    indent("JJ:     ", diff.stat(72)),
#  ),
#  surround("\nJJ: Diff:\n", "", indent("JJ:  ", diff.git(4)))
#)
#'''

commit_trailers = '''
if(!trailers.contains_key("Change-Id"), format_gerrit_change_id_trailer(self))'''

[colors]
"node" = { bold = true }
"node elided" = { fg = "bright black" }
"node working_copy" = { fg = "green" }
"node conflict" = { fg = "red" }
"node immutable" = { fg = "bright cyan" }
"node wip" = { fg = "yellow" }
"node normal" = { bold = false }
"commit_id prefix" = { bold = true }

"normal change_id" = { bold = true, fg = "magenta" }
"immutable change_id" = { bold = false, fg = "bright cyan" }

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
ls = ["log", "-T", "custom_log_summary"]
ll = ["log", "-T", "builtin_log_detailed"]
ld = ["log", "-T", "custom_log_summary", "-r", "develop::"]
add-changeid = ["--config-toml=ui.editor='.git/hooks/commit-msg'", "commit"]
changes = ["log", "-T", "custom_log_summary"]
sync = ["rebase", "--skip-emptied", "-s", "all:roots(develop..)", "-d", "develop"]
sync-features = ["rebase", "--skip-emptied", "-b", "all:bookmarks(glob:\"feature*\")", "-d", "develop"]
sync-main = ["rebase", "--skip-emptied", "-b", "all:bookmarks(glob:\"feature*\")", "-d", "main"]
sync-push = ["rebase", "--skip-emptied", "-b", "all:bookmarks(glob:\"push*\")", "-d", "main"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]
#review = ["git", "push", "--remote", "for-review"]
baseb = ["log", "--no-graph", "-r@-", "-Tlocal_bookmarks"]

[root]
bookmark = "develop"

[revsets]
log = "present(@) | ancestors(immutable_heads().., 3) | present(trunk())"
